repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.8.2
    hooks:
      - id: sqlfluff-fix
        entry: sqlfluff fix --force
        types: [ sql ]
        exclude: '^(?!schemas/)'
        additional_dependencies: [ '.[dbt]' ]
      - id: sqlfluff-lint
        types: [ sql ]
        exclude: '^(?!schemas/)'
        additional_dependencies: ['.[dbt]']
